[package]
name = "trollstov"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "A music player for the terminal where your files and their metadata are all you need."
homepage = "https://github.com/hikikones/troll/trollstov"
repository = "https://github.com/hikikones/troll/trollstov"
license.workspace = true
keywords = ["audio", "music", "player", "terminal", "tui"]
categories = ["command-line-utilities", "multimedia::audio"]

[dependencies]
clap = { workspace = true }
clap-cargo = { workspace = true }
directories = { workspace = true }
fastrand = { workspace = true }
ignore = { workspace = true }
image = { workspace = true }
indexmap = { workspace = true }
lofty = { workspace = true }
nucleo-matcher = { workspace = true }
ratatui = { workspace = true }
ratatui-image = { workspace = true }
rodio = { workspace = true }
seahash = { workspace = true }
serde = { workspace = true }
serde_repr = { workspace = true }
shared = { workspace = true }
souvlaki = { workspace = true }
terminal-colorsaurus = { workspace = true }
toml = { workspace = true }
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
utils = { workspace = true }
walkdir = { workspace = true }
widgets = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.44"
features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_LibraryLoader",
  "Win32_UI_WindowsAndMessaging"
]

[features]
default = []
opus = ["rodio/symphonia-libopus"]
